name: Helm Upgrade on Push to Main

on:
  push:
    branches:
      - main

jobs:
  helm-upgrade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '*'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build twine
          python -m pip install -r dags/requirements.txt

      - name: Check code quality
        run: make lint

    #   - name: Set up Kubernetes credentials
    #     # Assumes you're using a Kubeconfig secret stored in GitHub Actions
    #     run: |
    #       mkdir -p ~/.kube
    #       echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    #   - name: Install Helm
    #     uses: azure/setup-helm@v3

    #   - name: Run Helm upgrade (via Makefile)
    #     run: make upgrade
